name: Update Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essential for the bot to save changes to your README
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Scholar Publications
        uses: su-shubh/google-scholar-publications@v0.5.0
        with:
          user_id: LZmZFtMAAAAJ # Your Google Scholar ID
          max_publications: 5

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update latest publications" || exit 0
          git push
