name: Update Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * *' # This runs every night at midnight
  workflow_dispatch: # This allows you to run it manually to test

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Scholar
        uses: g-scholar/g-scholar-feed@v1.0.1
        with:
          user_id: LZmZFtMAAAAJ
          sort_by: pubdate
          max_publications: 5

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update latest publications from Google Scholar" || exit 0
          git push
